name: customized_streams
description: This library contains customized streams.
version: 1.0.13
author: Le Anh Dao <leanhdaoit@gmail.com>
homepage: https://github.com/dao-wkm/customized_streams

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ^0.39.8
  rxdart: 0.23.1

dev_dependencies:
  test: ^1.14.3
