name: customized_streams
description: This library contains customized streams.
version: 1.0.14
author: Le Anh Dao <leanhdaoit@gmail.com>
homepage: https://github.com/dao-wkm/customized_streams

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: 0.41.1
  rxdart: 0.25.0

dev_dependencies:
  test: ^1.15.7
